name: Setup workspace

inputs:
  uid:
    description: Component uid
    required: true

  version:
    description: Minecraft Version
    required: true
  lwjgl3:
    description: Lwjgl3
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      name: Setup Java 17
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - uses: actions/setup-java@v4
      name: Setup Java 16
      if: ${{ inputs.uid == 'net.minecraftforge' && inputs.version == '1.18.2' }}
      with:
        java-version: '16'
        distribution: 'temurin'

    - uses: actions/setup-java@v4
      name: Setup Java 21
      if: ${{ inputs.uid == 'net.minecraftforge' && inputs.version == '1.12.2' && inputs.lwjgl3 }}
      with:
        java-version: '16'
        distribution: 'temurin'
            
    - name: Install PSCompression
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module PSCompression

    - name: Create component directory
      shell: pwsh
      run: New-Item -Type Directory -Force component