on:
    workflow_dispatch:
      inputs:
        force:
          description: 'Force build of all jobs'
          required: false
          default: 'false'

env:
  LAUNCHER_VERSION: 5.6.x
  GH_TOKEN: ${{ github.token }}
  META_URL: "https://zmirror.storage.yandexcloud.net/meta/v1/servers-meta.zip"

name: Build Mirror Servers

jobs:
    build-server:
        runs-on: ubuntu-latest
        name: Build Server
        strategy:
            fail-fast: false
            matrix:
                version: ["1.16.5", "1.18.2", "1.19.2", "1.19.4", "1.20.1"]
                component: ["net.minecraftforge", "io.izzel.arclight"]
                exclude:
                  - version: "1.16.5"
                    component: "io.izzel.arclight" # arclight requires forge 36.2.39 while only 36.2.41 is available

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-java@v4
              name: Setup Java 17
              with:
                java-version: '17'
                distribution: 'temurin'

            - name: Download InstallUtil
              shell: pwsh
              run: |
                Invoke-RestMethod "https://mirror.zznty.ru/installutil/installutil" -OutFile "installutil"
                chmod +x installutil

            - name: Create component directory
              shell: pwsh
              run: New-Item -Type Directory -Force component

            - name: Get Latest Component Version
              id: meta
              shell: pwsh
              run: |
                if ("${{ matrix.component }}" -eq "net.minecraftforge" -and "${{ matrix.version }}" -eq "1.16.5") {
                  $version = "36.2.41"
                }
                elseif ("${{ matrix.component }}" -eq "io.izzel.arclight") {
                  $version = ./installutil component meta "${{ matrix.component }}" net.minecraft==${{ matrix.version }} --meta "${{ env.META_URL }}"
                }
                else {
                  $version = ./installutil component meta "${{ matrix.component }}" net.minecraft==${{ matrix.version }}
                }
                "version=$version" >> $env:GITHUB_OUTPUT

            - name: Get version suffix
              id: suffix
              shell: pwsh
              run: |
                if ("${{ matrix.component }}" -eq "net.minecraftforge") {
                  $value = "forge"
                }
                elseif ("${{ matrix.component }}" -eq "io.izzel.arclight") {
                  $value = "arclight"
                }
                else {
                  $value = "${{ matrix.component }}"
                }
                "value=$value" >> $env:GITHUB_OUTPUT

            - name: Get Mirror Component Version
              id: mirror
              shell: pwsh
              run: |
                $component = "${{ matrix.component }}"
                if ("${{ inputs.force }}" -eq "true") {
                  $version = $null
                }
                else {
                  $version = ./installutil component profile $component "${{ secrets.S3_ENDPOINT }}/${{ secrets.S3_BUCKET }}/${{ env.LAUNCHER_VERSION }}/servers/${{ matrix.version }}-${{ steps.suffix.outputs.value }}.json" legacy
                  if ($LASTEXITCODE -ne 0) {
                    Write-Host "No existing profile found (expected for first build)"
                    $version = $null
                  }
                }
                "version=$version" >> $env:GITHUB_OUTPUT

            - name: Install Component
              if: ${{ steps.meta.outputs.version != steps.mirror.outputs.version }}
              shell: pwsh
              working-directory: component
              run: |
                ../installutil install ${{ matrix.component }}==${{ steps.meta.outputs.version }} net.minecraft==${{ matrix.version }} -p GravitServer --meta "${{ env.META_URL }}" --mirror "https://mirror.gravitlauncher.com/${{ env.LAUNCHER_VERSION }}/"
            
            - name: Build files to upload
              if: ${{ steps.meta.outputs.version != steps.mirror.outputs.version }}
              working-directory: component
              run: |
                rm -rf mmc
                7z a -sdel "${{ matrix.version }}-${{ steps.suffix.outputs.value }}.zip" ./*
            
            - name: Upload profile
              if: ${{ steps.meta.outputs.version != steps.mirror.outputs.version }}
              working-directory: component
              run: aws s3 --endpoint-url=${{ secrets.S3_ENDPOINT }} sync . s3://${{ secrets.S3_BUCKET }}/${{ env.LAUNCHER_VERSION }}/servers/
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.S3_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_KEY }}
                AWS_DEFAULT_REGION: ru-central1
                AWS_REQUEST_CHECKSUM_CALCULATION: when_required
                AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
